apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: {{app}}
  namespace: {{namespace}}
  labels:
    team: {{team}}
    app: {{app}}
spec:
  image: {{image}}
  port: 7000
  liveness:
    path: {{base_path}}/isAlive
    timeout: 1
    periodSeconds: 5
    failureThreshold: 10
  readiness:
    path: {{base_path}}/isReady
    timeout: 1
  prometheus:
    enabled: false
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 75
  resources:
    limits:
      cpu: 500m
      memory: 1024Mi
    requests:
      cpu: 300m
      memory: 512Mi
  ingresses:
  {{#each ingresses as |ingress|}}
     - {{ingress}}
  {{/each}}
  sessionAffinity: ClientIP # Sticky Session for ingress controller to prevent 404 on rollout
  env:
    - name: BASE_PATH
      value: {{base_path}}
    - name: DITTNAV_PERSONALIA_URL
      value: {{dittnav_personalia_url}}
    - name: DITTNAV_GENERELLE_FLISER_URL
      value: {{dittnav_generelle-fliser-url}}
    - name: VTA_URL
      value: {{vta_url}}
    - name: VTA_SITUASJON_URL
      value: {{vta_situasjon_url}}
    - name: VTA_OKONOMI_URL
      value: {{vta_okonomi_url}}
    - name: DECORATOR_URL
      value: {{decorator_url}}
  accessPolicy:
    outbound:
      external:
      {{#each podlet_hosts as |host|}}
        - host: {{host}}
      {{/each}}
